// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Telemetry interface {
	IsTelemetry()
}

type Device struct {
	ID string `json:"id"`
}

func (Device) IsEntity() {}

type Origin struct {
	Device *Device        `json:"device"`
	Pos    *WGS84Position `json:"pos"`
}

type Temperature struct {
	From *Origin `json:"from"`
	When string  `json:"when"`
	Temp float64 `json:"temp"`
}

func (Temperature) IsTelemetry() {}

type WGS84Position struct {
	Lon float64 `json:"lon"`
	Lat float64 `json:"lat"`
}
